# Copyright (c) 2018-2019 The Ion developers
# Copyright (c) 2019 The OBSR developers
name: obsr
version: v1.1.01
summary:   peer-to-peer network based digital currency
description: |
  Obsr is a free open source peer-to-peer electronic cash system that
  is completely decentralized, without the need for a central server or
  trusted parties.  Users hold the crypto keys to their own money and
  transact directly with each other, with the help of a P2P network to
  check for double-spending.

grade: stable
confinement: strict
icon: share/pixmaps/bitcoin256.png
apps:
  daemon:
    command: obsrd
    plugs: [network, network-bind, home, removable-media]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  daemon-testnet:
    command: obsrd --testnet
    plugs: [network, network-bind, home, removable-media]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  daemon-regtest:
    command: obsrd --regtest
    plugs: [network, network-bind, home, removable-media]
  qt:
    command: desktop-launch obsr-qt
    plugs: [network, network-bind, unity7, unity8-calendar, unity8-contacts, desktop, desktop-legacy, wayland, x11, mir, opengl, home, removable-media]
    desktop: qt.desktop
  qt-testnet:
    command: desktop-launch obsr-qt --testnet
    plugs: [network, network-bind, unity7, unity8-calendar, unity8-contacts, desktop, desktop-legacy, wayland, x11, mir, opengl, home, removable-media]
    desktop: qt-testnet.desktop
  qt-regtest:
    command: desktop-launch obsr-qt --regtest
    plugs: [network, network-bind, unity7, unity8-calendar, unity8-contacts, desktop, desktop-legacy, wayland, x11, mir, opengl, home, removable-media]
    desktop: qt-regtest.desktop
  cli:
    command: obsr-cli
    plugs: [network, network-bind, home]
  cli-testnet:
    command: obsr-cli --testnet
    plugs: [network, network-bind, home]
  cli-regtest:
    command: obsr-cli --regtest
    plugs: [network, network-bind, home]
  tx:
    command: obsr-tx
    plugs: [home]
parts:
  obsr:
    source: https://github.com/observernet/obsr
    source-type: git
    source-tag: v1.1.01
    plugin: nil
    override-build: |
      # print glib version
      # powerpc64le-linux-gnu (Ubuntu GLIBC 2.23-0ubuntu11) 2.23)
      echo "GLIBC version:"
      ldd --version
      # Patch - Default home folder
      ## We don't want to copy the full blockchain every time that the snap is   
      ## updated, but there's no way to define a default data dir in obsr-qt.
      ## Additionaly we fix funcs.mk
      echo "apply patches:"
      git apply $SNAPCRAFT_STAGE/default_data_dir.patch
      git apply $SNAPCRAFT_STAGE/fix-bdb-tmp-folder.patch
      ## Patch - Fix Bug extracting sources without ownership
      sed -i 's/tar --strip-components/tar --no-same-owner --strip-components/' $SNAPCRAFT_PART_BUILD/depends/funcs.mk
      # Build Dependencies
      echo "START BUILDING FOR $SNAPCRAFT_ARCH_TRIPLET architecture"
      cd $SNAPCRAFT_PART_BUILD/depends
      # Fix building ARM and AARCh64, as on some point they fail with, predownload all packages
      #   curl: (22) The requested URL returned error: 407
      make download-linux
      if [ $SNAPCRAFT_ARCH_TRIPLET = "i386-linux-gnu" ]
      then
        make HOST=i686-linux-gnu
      elif [ $SNAPCRAFT_ARCH_TRIPLET = "arm-linux-gnueabihf" ]
      then
        update-alternatives --install /usr/bin/arm-linux-gnueabihf-gcc \
        arm-linux-gnueabihf-gcc /usr/bin/arm-linux-gnueabihf-gcc-4.8 100
        update-alternatives --install /usr/bin/arm-linux-gnueabihf-g++ \
        arm-linux-gnueabihf-g++ /usr/bin/arm-linux-gnueabihf-g++-4.8 100
        make HOST=$SNAPCRAFT_ARCH_TRIPLET -j4
      else
        make HOST=$SNAPCRAFT_ARCH_TRIPLET -j4
      fi
      # Configure Observer Core
      cd $SNAPCRAFT_PART_BUILD
      echo "Configure and build OBSR"
      ./autogen.sh
      if [ $SNAPCRAFT_ARCH_TRIPLET = "i386-linux-gnu" ]
      then
        ./configure --prefix=`pwd`/depends/i686-linux-gnu
      else
        ./configure --prefix=`pwd`/depends/$SNAPCRAFT_ARCH_TRIPLET
      fi
      # Compile Observer Core
      make -j4
      # strip symbols
      BINARIES="obsrd obsr-cli obsr-tx qt/obsr-qt test/test_obsr"
      for b in $BINARIES; do
        if [ -e src/${b} ]; then
          echo "Strip binary src/${b}"
          strip src/${b}
        fi
      done
      # Install Observer Core
      make install prefix=$SNAPCRAFT_PART_INSTALL
      # print in log which files are installed
      echo "Installed files:"
      find $SNAPCRAFT_PART_INSTALL -type f
    build-packages:
      - curl
      - wget
      - g++
      - gcc
      - make
      - autoconf
      - automake
      - cmake
      - pkg-config
      - libtool
      - bsdmainutils
      - binutils
      - python3
    stage-packages: [ca-certificates]
    after:
      - desktop-qt5
      - patches
  desktop-qt5:
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
      - qtwayland5
  patches:
    source: snap/patches
    plugin: dump
    prime:
      - -*
  desktop:
    source: snap/usr/share/applications
    plugin: dump
